package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Shape = 2;
  public static final int Square = 3;
  public static final int Triangle = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x1952f8d055204656L, 0xa76337b6f950f125L);
    builder.put(0x6ab6e004fd886aaaL, Canvas);
    builder.put(0x6ab6e004fd886aa2L, Circle);
    builder.put(0x6ab6e004fd886aa0L, Shape);
    builder.put(0x6ab6e004fd886aa6L, Square);
    builder.put(0x1a431ea7673619efL, Triangle);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
